new icon:
  - any: [icons/*.svg]
    status: added
update icon/data:
  - any: [icons/*.svg]
    status: modified
  - all: [data/simple-icons.json]
    status: modified
breaking change:
  - any: [icons/*.svg]
    status: removed
docs:
  - any: ['*.md']
    status: modified
meta:
  - any:
      [
        '.github/*',
        'scripts/*',
        'tests/*',
        '.husky/*',
        '*.mjs',
        '*.d.ts',
        '*.json',
        '*.toml',
        '*',
      ]
    status: modified
dependencies:
  - all: ['package-lock.json']
    status: modified
