name: Icon update
description: Help us improve by reporting outdated icons
labels: [update icon/data]
title: 'Update: <brand-name>'

body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `update icon/data` label][update-icon-data-issues]
        (including closed issues) before you continue. If you find one for the brand
        you're reporting then leave a comment on it or add a reaction.

        [update-icon-data-issues]: https://github.com/simple-icons/simple-icons/labels/update%20icon/data

  - type: input
    attributes:
      label: Brand Name
      placeholder: 'Example: Simple Icons'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official Resources for Icon and Color
      description: |
        Media kits, brand guidelines, SVG files, etc. You can set
        this to "None" if you are unable to find any resources.
      placeholder: |
        Example:
        svg: https://github.com/simple-icons/simple-icons/blob/develop/icons/simpleicons.svg
        color: `#111111`, from the website header
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the brand? Remember that not everyone knows the brand as well as you do. For example:
        - Are there multiple options for the logo and/or color?
        - Is the icon released under a license?
      placeholder: 'Example: There are two variants of this icon...'
