name: Icon request
description: Request a new icon for Simple Icons
labels: [new icon]
title: 'Request: <brand-name>'

body:
  - type: markdown
    attributes:
      value: |
        We won't add non-brand icons or anything related to illegal services. If in
        doubt, open an issue and we'll have a look. For more details see the
        [Contributing Guidelines].

        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `new icon` label][new-icon-issues]
        (including closed issues) before you continue. If you find one for the brand
        you're requesting then leave a comment on it or add a reaction.

        > [!TIP]
        > In order to view website rankings on `similarweb.com`:
        > Go to `https://similarweb.com/website`, enter the website address, and click on Analyze Traffic.

        [contributing guidelines]: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

        [new-icon-issues]: https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3A%22new+icon%22

  - type: input
    attributes:
      label: Brand Name
      placeholder: 'Example: Simple Icons'
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: |
        For non-web brands you can add a relevant link. You can put "None" if you don't
        think there's a website.
      placeholder: 'Example: https://simpleicons.org'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Popularity Metric
      description: |
        Provide either a [Similarweb rank], which must be in the top 500,000 to qualify,
        or failing that another metric from [our contributing guidelines] that we can
        use to assess the popularity of the requested brand.

        [Similarweb rank]: https://www.similarweb.com
        [our contributing guidelines]: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity
      placeholder: 'Example: The Similarweb rank is 261,758. See https://www.similarweb.com/website/simpleicons.org'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official Resources for Icon and Color
      description: |
        Media kits, brand guidelines, SVG files, etc. You can set
        this to "None" if you are unable to find any resources.
      placeholder: |
        Example:
        - SVG: https://github.com/simple-icons/simple-icons/blob/develop/icons/simpleicons.svg
        - Color: `#111111`, from the website header
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the brand? Remember that not everyone knows the brand as well as you do. For example:
        - Are there multiple options for the logo and/or color?
        - Is the icon released under a license?
        - If you think the brand might not be accepted, why do you think it should be considered?
      placeholder: 'Example: There are two variants of this icon...'
