name: Icon request
description: Request a new icon for Simple Icons
labels: [new icon]

body:
  - type: markdown
    attributes:
      value: >-
        We won't add non-brand icons or anything related to illegal services. If in
        doubt, open an issue and we'll have a look. For more details see the
        [Contributing Guidelines].


        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `new icon` label][new-icon-issues]
        (including closed issues) before you continue. If you find one for the brand
        you're requesting then leave a comment on it or add a reaction.


        [contributing guidelines]: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

        [new-icon-issues]: https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3A%22new+icon%22+is%3Aopen

  - type: input
    attributes:
      label: Brand Name
      placeholder: 'Example: Simple Icons'
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: >-
        For non-web brands you can add a relevant link. You can put "None" if you don't
        think there's a website.
      placeholder: 'Example: https://simpleicons.org'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Popularity Metric
      description: >-
        Provide either a [Similarweb rank] or the number of GitHub stars. If Similarweb does not have a rank for your brand or the rank fails to meet our requirements, we can also accept an [Alexa rank] as an alternative. If these are not
        available or too low you can still open the issue. In this case, please
        provide any information regarding the brand's popularity you think is
        relevant.


        [Similarweb rank]: https://www.similarweb.com
        [Alexa rank]: https://www.alexa.com/siteinfo
      placeholder: 'Example: The Alexa rank is 249,089. See https://www.alexa.com/siteinfo/simpleicons.org'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official Resources for Icon and Color
      description: >-
        Media kits, brand guidelines, SVG files, etc. You can set
        this to "None" if you are unable to find any resources.
      placeholder: |
        Example:
        svg: https://github.com/simple-icons/simple-icons/blob/develop/icons/simpleicons.svg
        color: `#111111`, from the website header
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the brand? Remember that not everyone knows the brand as well as you do. For example:
        - Are there multiple options for the logo and/or color?
        - Is the icon released under a license?
        - If you think the brand might not be accepted, why do you think it should be considered?
      placeholder: 'Example: There are two variants of this icon...'

  - type: dropdown
    attributes:
      label: Contributing
      description: >-
        This is an open source project and we welcome contributions. Do you want to
        add this icon?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
