# If some workflows are executed in a fork, we don't want to run them
# because would fail due to missing permissions and will generate
# noise for activity watchers.

name: Check if running in a fork
description: Check if a workflow is running in a forked repository and set an output accordingly.

inputs:
  in-fork-message:
    description: Message to display when the workflow is running in a fork.
    required: true
outputs:
  is-fork:
    description: Indicates if the current repository is a fork.
    value: ${{ steps.check-is-fork.outputs.is-fork }}

runs:
  using: composite
  steps:
    - id: check-is-fork
      shell: bash
      run: |
        if [ "${{ github.repository_owner }}" != "simple-icons" ]; then
          echo "is-fork=true" >> $GITHUB_OUTPUT
          echo "${{ inputs.in-fork-message }}"
        else
          echo "is-fork=false" >> $GITHUB_OUTPUT
        fi
