#!/usr/bin/env sh
# ^^^^^^^^^^^^^^^ Husky doesn't require this shebang,
# but code editors need it to recognize the file as a script.

# Format and add the changes to the staging area
npm run format
git add -u

# POSIX shell (sh) run time parameters.
#   -e: Exit immediately if a command exits with a non-zero status.
#   -u: Treat unset variables as errors when substituting.
set -eu

# Track exit code in case that we want to add other lints in the future
EXITCODE=0

# If there are changed icons, lint them with SVGLint
changed_icons="$(git diff --cached --name-only | grep '^icons/' | xargs)"
if [ -n "$changed_icons" ]; then
	# Parse the `svglint` script from package.json
	svglint_script="$(grep -m1 '"svglint"' package.json | cut -d'"' -f4)"
	# Remove the last argument (the files to lint)
	svglint_script_no_icons="$(echo "$svglint_script" | rev | cut -d' ' -f2- | rev)"
	# Execute it for the changed icons
	echo "+ npx $svglint_script_no_icons" "$changed_icons"
	npx $svglint_script_no_icons $changed_icons || EXITCODE=$?
fi

exit $EXITCODE
